In [56]:
import numpy as np
import pandas as pd

import importlib
importlib.reload(utils)
import sys
sys.path.append("../../utils")
import analysis_untilities as utils

In [139]:
aidata = pd.read_csv("AI Job Market Dataset.csv")

In [33]:
aidata.head()

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2

In [140]:
importlib.reload(utils)
utils.overview(aidata)

No.Rows: 10345
No.Columns: 19
Columns:
  - job_id                  (10345 Uniques) (0 nulls)  int64
  - job_title               (6 Uniques)     (0 nulls)  object
  - company_size            (4 Uniques)     (0 nulls)  object
  - company_industry        (6 Uniques)     (0 nulls)  object
  - country                 (7 Uniques)     (0 nulls)  object
  - remote_type             (3 Uniques)     (0 nulls)  object
  - experience_level        (3 Uniques)     (0 nulls)  object
  - years_experience        (15 Uniques)    (0 nulls)  int64
  - education_level         (3 Uniques)     (0 nulls)  object
  - skills_python           (2 Uniques)     (0 nulls)  int64
  - skills_sql              (2 Uniques)     (0 nulls)  int64
  - skills_ml               (2 Uniques)     (0 nulls)  int64
  - skills_deep_learning    (2 Uniques)     (0 nulls)  int64
  - skills_cloud            (2 Uniques)     (0 nulls)  int64
  - salary                  (9901 Uniques)  (0 nulls)  int64
  - job_posting_month       (12 Uniques)    (0 nulls)  int64
  - job_posting_year        (7 Uniques)     (0 nulls)  int64
  - hiring_urgency          (3 Uniques)     (0 nulls)  object
  - job_openings            (9 Uniques)     (0 nulls)  int64

In [160]:
filter_country = aidata.loc[aidata.country=="Australia"]
titles_aus = filter_country.groupby("job_title").size()
titles_aus

job_title
AI Engineer                  233
Business Analyst             248
Data Analyst                 219
Data Engineer                228
Data Scientist               275
Machine Learning Engineer    252
dtype: int64

In [163]:
education_aus = filter_country.groupby("education_level").size()
education_aus

education_level
Bachelor    462
Master      511
PhD         482
dtype: int64

In [177]:
filter_country_education = aidata.loc[(aidata.country=="Australia") 
                                      & (aidata.education_level=="Bachelor")
                                      & (~aidata.experience_level.isin(["Senior", "Mid"]))
                                      & (aidata.job_posting_year==2026)
                                      ]
filter_country_education

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
187,188,Business Analyst,Medium,Education,Australia,Remote,Entry,6,Bachelor,0,1,0,1,0,64431,10,2026,High,8
1150,1151,Machine Learning Engineer,Medium,E-commerce,Australia,Onsite,Entry,13,Bachelor,1,1,1,0,1,116989,8,2026,Medium,1
1485,1486,AI Engineer,Startup,Retail,Australia,Hybrid,Entry,2,Bachelor,1,0,0,0,0,91317,10,2026,Low,2
1503,1504,Machine Learning Engineer,Startup,E-commerce,Australia,Onsite,Entry,1,Bachelor,1,1,0,1,0,101762,9,2026,Low,2
2429,2430,AI Engineer,MNC,Finance,Australia,Onsite,Entry,8,Bachelor,0,1,1,1,0,143352,9,2026,High,1
3330,3331,Data Engineer,Medium,Technology,Australia,Remote,Entry,0,Bachelor,0,1,1,1,0,78662,9,2026,High,6
3386,3387,Data Scientist,MNC,Education,Australia,Remote,Entry,14,Bachelor,0,0,1,0,1,93973,9,2026,Medium,1
4069,4070,Business Analyst,Medium,Finance,Australia,Hybrid,Entry,7,Bachelor,1,1,1,1,1,94170,9,2026,High,4
4918,4919,Data Engineer,Medium,Finance,Australia,Remote,Entry,2,Bachelor,0,0,1,0,0,65978,6,2026,Low,6
4937,4938,Machine Learning Engineer,MNC,E-commerce,Australia,Hybrid,Entry,1,Bachelor,1,0,1,0,1,135386,12,2026,High,9
5241,5242,AI Engineer,Medium,Healthcare,Australia,Remote,Entry,2,Bachelor,1,0,0,1,0,101518,3,2026,Low,6
5543,5544,Data Engineer,Startup,Technology,Australia,Hybrid,Entry,6,Bachelor,0,1,0,0,1,61251,5,2026,High,7
6176,6177,Data Analyst,Medium,Finance,Australia,Onsite,Entry,0,Bachelor,1,1,1,0,0,61753,4,2026,Low,5
6506,6507,Data Engineer,MNC,E-commerce,Australia,Hybrid,Entry,6,Bachelor,1,1,1,0,1,92244,6,2026,Low,1
7937,7938,Data Engineer,Medium,Finance,Australia,Remote,Entry,5,Bachelor,1,0,1,0,0,61900,10,2026,High,9
8133,8134,Data Scientist,Medium,E-commerce,Australia,Hybrid,Entry,3,Bachelor,0,0,0,0,0,53150,3,2026,Low,5
8177,8178,Data Scientist,Medium,Technology,Australia,Onsite,Entry,2,Bachelor,1,1,1,0,0,65508,10,2026,Low,3
8707,8708,AI Engineer,Startup,Education,Australia,Remote,Entry,1,Bachelor,1,1,0,1,1,116465,5,2026,Low,6
9814,9815,AI Engineer,Enterprise,Retail,Australia,Remote,Entry,7,Bachelor,0,0,1,0,1,110064,10,2026,High,9
10223,10224,Data Scientist,Enterprise,Education,Australia,Hybrid,Entry,4,Bachelor,0,0,0,0,0,50194,12,2026,Low,3

In [176]:
filter_country_education.job_posting_year.dtypes

dtype('int64')